In [2]:
#all imports needed 
import pandas as pd

In [13]:
#importing data for 2024 
# Load the 2024 race results CSV
results_2024 = pd.read_csv("f1_2024(Sheet1).csv")
# Preview the first few rows
results_2024.head()

,GRAND PRIX,DATE,WINNER,TEAM,LAPS,TIME
0,Bahrain,2-Mar,Max Verstappen,Red Bull Racing Honda RBPT,57.0,31:44.7
1,Saudi Arabia,9-Mar,Max Verstappen,Red Bull Racing Honda RBPT,50.0,20:43.3
2,Australia,24-Mar,Carlos Sainz,Ferrari,58.0,20:26.8
3,Japan,7-Apr,Max Verstappen,Red Bull Racing Honda RBPT,53.0,54:23.6
4,China,21-Apr,Max Verstappen,Red Bull Racing Honda RBPT,56.0,40:52.6

In [14]:
#importing data for 2023
# Load the 2023 race results CSV
results_2023 = pd.read_csv("f1_2023(Sheet1).csv")
# Preview the first few rows
results_2023.head()

,GRAND PRIX,DATE,WINNER,TEAM,LAPS,TIME
0,Bahrain,5-Mar,Max Verstappen,Red Bull Racing Honda RBPT,57.0,33:56.7
1,Saudi Arabia,19-Mar,Sergio Perez,Red Bull Racing Honda RBPT,50.0,21:14.9
2,Australia,2-Apr,Max Verstappen,Red Bull Racing Honda RBPT,58.0,32:38.4
3,Azerbaijan,30-Apr,Sergio Perez,Red Bull Racing Honda RBPT,51.0,32:42.4
4,Miami,7-May,Max Verstappen,Red Bull Racing Honda RBPT,57.0,27:38.2

In [15]:
#importing data for 2022
# Load the 2022 race results CSV
results_2022 = pd.read_csv("f1_2022(Sheet1).csv")
# Preview the first few rows
results_2022.head()

,GRAND PRIX,DATE,WINNER,TEAM,LAPS,TIME
0,Bahrain,20-Mar,Charles Leclerc,Ferrari,57.0,37:33.6
1,Saudi Arabia,27-Mar,Max Verstappen,Red Bull Racing RBPT,50.0,24:19.3
2,Australia,10-Apr,Charles Leclerc,Ferrari,58.0,27:46.5
3,Emilia-Romagna,24-Apr,Max Verstappen,Red Bull Racing RBPT,63.0,32:08.0
4,Miami,8-May,Max Verstappen,Red Bull Racing RBPT,57.0,34:24.3

In [17]:
#importing data for 2021
# Load the 2021 race results CSV
results_2021 = pd.read_csv("f1_2021(Sheet1).csv")
# Preview the first few rows
results_2021.head()

,GRAND PRIX,DATE,WINNER,TEAM,LAPS,TIME
0,Bahrain,28-Mar,Lewis Hamilton,Mercedes,56.0,32:03.9
1,Emilia-Romagna,18-Apr,Max Verstappen,Red Bull Racing Honda,63.0,02:34.6
2,Portugal,2-May,Lewis Hamilton,Mercedes,66.0,34:31.4
3,Spain,9-May,Lewis Hamilton,Mercedes,66.0,33:07.7
4,Monaco,23-May,Max Verstappen,Red Bull Racing Honda,78.0,38:56.8

In [18]:
#importing data for 2020
# Load the 2020 race results CSV
results_2020 = pd.read_csv("f1_2020(Sheet1).csv")
# Preview the first few rows
results_2020.head()

,GRAND PRIX,DATE,WINNER,TEAM,LAPS,TIME
0,Austria,5-Jul,Valtteri Bottas,Mercedes,71.0,30:55.7
1,Styria,12-Jul,Lewis Hamilton,Mercedes,71.0,22:50.7
2,Hungary,19-Jul,Lewis Hamilton,Mercedes,70.0,36:12.5
3,Great Britain,2-Aug,Lewis Hamilton,Mercedes,52.0,28:01.3
4,70th Anniversary,9-Aug,Max Verstappen,Red Bull Racing Honda,52.0,19:42.0

In [4]:
#importing data for 2019
# Load the 2020 race results CSV
results_2019 = pd.read_csv("f1_2019(Sheet1).csv")
# Preview the first few rows
results_2019.head()

   GRAND PRIX    DATE           WINNER      TEAM  LAPS     TIME
0   Australia  17-Mar  Valtteri Bottas  Mercedes  58.0  25:27.3
1     Bahrain  31-Mar   Lewis Hamilton  Mercedes  57.0  34:21.3
2       China  14-Apr   Lewis Hamilton  Mercedes  56.0  32:06.4
3  Azerbaijan  28-Apr  Valtteri Bottas  Mercedes  51.0  31:52.9
4       Spain  12-May   Lewis Hamilton  Mercedes  66.0  35:50.4

In [5]:
#importing data for 2018
# Load the 2020 race results CSV
results_2018 = pd.read_csv("f1_2018(Sheet1).csv")
# Preview the first few rows
results_2018.head()

,GRAND PRIX,DATE,WINNER,TEAM,LAPS,TIME
0,Australia,25-Mar,Sebastian Vettel,Ferrari,58.0,29:33.3
1,Bahrain,8-Apr,Sebastian Vettel,Ferrari,57.0,32:01.9
2,China,15-Apr,Daniel Ricciardo,Red Bull Racing TAG Heuer,56.0,35:36.4
3,Azerbaijan,29-Apr,Lewis Hamilton,Mercedes,51.0,43:44.3
4,Spain,13-May,Lewis Hamilton,Mercedes,66.0,35:30.0

In [6]:
#importing data for 2017
# Load the 2017 race results CSV
results_2017 = pd.read_csv("f1_2017(Sheet1).csv")
# Preview the first few rows
results_2017.head()

  GRAND PRIX    DATE            WINNER      TEAM  LAPS     TIME
0  Australia  26-Mar  Sebastian Vettel   Ferrari  57.0  24:11.7
1      China   9-Apr    Lewis Hamilton  Mercedes  56.0  37:36.2
2    Bahrain  16-Apr  Sebastian Vettel   Ferrari  57.0  33:53.4
3     Russia  30-Apr   Valtteri Bottas  Mercedes  52.0  28:08.7
4      Spain  14-May    Lewis Hamilton  Mercedes  66.0  35:56.5

In [7]:
#importing data for 2016
# Load the 2016 race results CSV
results_2016 = pd.read_csv("f1_2016(Sheet1).csv")
# Preview the first few rows
results_2016.head()

  GRAND PRIX    DATE          WINNER                       TEAM  LAPS     TIME
0  Australia  20-Mar    Nico Rosberg                   Mercedes  57.0  48:15.6
1    Bahrain   3-Apr    Nico Rosberg                   Mercedes  57.0  33:34.7
2      China  17-Apr    Nico Rosberg                   Mercedes  56.0  38:53.9
3     Russia   1-May    Nico Rosberg                   Mercedes  53.0  32:42.0
4      Spain  15-May  Max Verstappen  Red Bull Racing TAG Heuer  66.0  41:40.0

In [8]:
#importing data for 2015
# Load the 2015 race results CSV
results_2015 = pd.read_csv("f1_2015(Sheet1).csv")
# Preview the first few rows
results_2015.head()

  GRAND PRIX    DATE            WINNER      TEAM  LAPS     TIME
0  Australia  15-Mar    Lewis Hamilton  Mercedes  58.0  31:54.1
1   Malaysia  29-Mar  Sebastian Vettel   Ferrari  56.0  41:05.8
2      China  12-Apr    Lewis Hamilton  Mercedes  56.0  39:42.0
3    Bahrain  19-Apr    Lewis Hamilton  Mercedes  57.0  35:05.8
4      Spain  10-May      Nico Rosberg  Mercedes  66.0  41:12.6